Repository AthosFatecSjc/server, pull requests merged in 2025-09, with the labels that each got.

#6 ATHOS-06 Retorna o objeto view na rota do relatório produtividade
  apps/relatorios/produtividade/templates/produtividade/index.html
  apps/relatorios/produtividade/views.py
  config/settings.py
  config/urls.py
Labels: enhancement

#7 ATHOS-40 Criado mapeamento do banco de dados
  apps/relatorios/migrations/0001_initial.py
  apps/relatorios/migrations/__init__.py
  apps/relatorios/models.py
  config/settings.py
Labels: enhancement

#11 ATHOS-15 Cria tabela total de horas consolidadas por projeto front integracao
  apps/relatorios/admin.py
  apps/relatorios/atividade/services.py
  apps/relatorios/atividade/static/atividade/js/htmx.min.js
  apps/relatorios/atividade/templates/atividade/index.html
  apps/relatorios/atividade/templates/atividade/partials/_tabela_e_cards.html
  apps/relatorios/atividade/templatetags/__init__.py
  apps/relatorios/atividade/templatetags/custom_filters.py
  apps/relatorios/atividade/urls.py
  apps/relatorios/atividade/views.py
  config/settings.py
  config/urls.py
  requirements.txt
Labels: enhancement

#15 ATHOS-52 Adiciona infra do banco
  .env.example
  .github/workflows/django.yml
  config/settings.py
  docker-compose.yml
Labels: enhancement

#17 ATHOS-10 Cria e integra a tabela calendário no front
  apps/relatorios/migrations/0002_rename_objetivo_estagirario_metatempocontrole_objetivo_estagiario.py
  apps/relatorios/models.py
  apps/relatorios/produtividade/services.py
  apps/relatorios/produtividade/templates/produtividade/index.html
  apps/relatorios/produtividade/urls.py
  apps/relatorios/produtividade/views.py
Labels: enhancement

#23 ATHOS-38 Criar input para legenda em caso de FO , FE , AT e input para Meta (back e front)
  apps/relatorios/produtividade/services.py
  apps/relatorios/produtividade/templates/produtividade/index.html
  apps/relatorios/produtividade/urls.py
  apps/relatorios/produtividade/views.py
Labels: enhancement

#26 ATHOS-82 Adiciona script SQL para inserção de dados
  banco/insert.sql
Labels: documentation

#29 ATHOS-35 Aplicar filtros para geracao de relatorios
  apps/relatorios/atividade/templates/atividade/index.html
  apps/relatorios/comparacao/services.py
  apps/relatorios/comparacao/templates/comparacao/index.html
  apps/relatorios/comparacao/views.py
  config/settings.py
  static/js/htmx.min.js
Labels: enhancement

#30 ATHOS-32 Criar tabela total de horas por colaborador - Prevista x Realizadas (front e integracao)
  apps/relatorios/comparacao/templates/comparacao/index.html
Labels: enhancement

#38 ATHOS-97 Ajustado graficos para exibição de todos os dados
  apps/relatorios/atividade/templates/atividade/index.html
  apps/relatorios/atividade/templates/atividade/partials/_grafico_pizza.html
Labels: bug

#31 ATHOS-33 Criar gráfico para total de horas por desenvolvedor (front integracao)
  apps/relatorios/comparacao/templates/comparacao/index.html
Labels: enhancement

#34 ATHOS-34 Criar grafico comparativo de horas realizadas x previstas
  apps/relatorios/comparacao/templates/comparacao/index.html
Labels: enhancement

#35 ATHOS-36 Criar a função de exportação (front + back)
  apps/relatorios/comparacao/services.py
  apps/relatorios/comparacao/templates/comparacao/index.html
  apps/relatorios/comparacao/urls.py
  apps/relatorios/comparacao/views.py
Labels: enhancement

#37 ATHOS-96 Ajustar titulos
  apps/relatorios/atividade/templates/atividade/partials/_tabela_e_cards.html
  apps/relatorios/atividade/templates/atividade/partials/_tabela_horas_dev.html
  apps/relatorios/atividade/views.py
Labels: bug

#40 ATHOS-95 Ajustar exportar Atividade
  apps/relatorios/atividade/services.py
  apps/relatorios/atividade/templates/atividade/partials/_tabela_e_cards.html
  requirements.txt
Labels: bug

#42 ATHOS-98 Criacao de funcao para legendar users do grafico
  apps/relatorios/comparacao/services.py
  apps/relatorios/comparacao/templates/comparacao/index.html
  apps/relatorios/templates/relatorios/index.html
Labels: bug
